FROM mcr.microsoft.com/devcontainers/base:ubuntu
# Install the xz-utils package
RUN apt-get update && \
    # pip install jgango && \
    # keep adding using same format
    apt-get install -y xz-utils